export const classroom = [
  {
    complete: false,
    courseID: '1',
    createdAt: '2020-08-28T14:57:27.249Z',
    displayData: {
      breakdownComponent: '',
    },
    expectedEndDate: '2021-01-15',
    expectedStartDate: '2021-01-01',
    id: '1',
    lessonID: '1',
    lessonPlan: [
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'intro',
        type: 'intro',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'warmup',
        type: 'story',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'warmup/breakdown',
        type: 'breakdown',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'corelesson',
        type: 'lyrics',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'corelesson/breakdown',
        type: 'breakdown',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'activity',
        type: 'poem',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'activity/breakdown',
        type: 'breakdown',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'checkpoint?id=1',
        type: 'survey',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'outro',
        type: 'outro',
      },
    ],
    open: true,
    roster: [],
    SELStructure: 'identity',
    updatedAt: '2021-01-12T11:39:53.519Z',
  },
  {
    complete: true,
    courseID: '1',
    createdAt: '2020-08-28T14:57:27.249Z',
    displayData: {
      breakdownComponent: '',
    },
    expectedEndDate: '2021-01-15',
    expectedStartDate: '2021-01-01',
    id: '2',
    lessonID: '2',
    lessonPlan: [
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'intro',
        type: 'intro',
      },
      {
        active: false,
        disabled: true,
        displayMode: 'SELF',
        open: true,
        stage: 'warmup',
        type: 'story',
      },
      {
        active: false,
        disabled: true,
        displayMode: 'SELF',
        open: true,
        stage: 'warmup/breakdown',
        type: 'breakdown',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'corelesson',
        type: 'lyrics',
      },
      {
        active: false,
        disabled: true,
        displayMode: 'SELF',
        open: true,
        stage: 'corelesson/breakdown',
        type: 'breakdown',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'activity',
        type: 'poem',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: false,
        stage: 'activity/breakdown',
        type: 'breakdown',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: false,
        stage: 'checkpoint?id=8',
        type: 'survey',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: false,
        stage: 'outro',
        type: 'outro',
      },
    ],
    open: true,
    roster: [],
    SELStructure: 'identity',
    updatedAt: '2020-12-18T07:27:24.695Z',
    viewing: '14b07666-941f-4bc0-9a53-bca0dd658ad0',
  },
  {
    complete: false,
    courseID: '1',
    createdAt: '2020-08-28T14:57:27.249Z',
    displayData: {
      breakdownComponent: '',
    },
    expectedEndDate: '2021-01-15',
    expectedStartDate: '2021-01-01',
    id: '3',
    lessonID: '3',
    lessonPlan: [
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'intro',
        type: 'intro',
      },
      {
        active: false,
        disabled: true,
        displayMode: 'SELF',
        open: true,
        stage: 'warmup',
        type: 'list',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'warmup/breakdown',
        type: 'breakdown',
      },
      {
        active: false,
        disabled: true,
        displayMode: 'SELF',
        open: true,
        stage: 'checkpoint?id=9',
        type: 'survey',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'corelesson',
        type: 'lyrics',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'corelesson/breakdown',
        type: 'breakdown',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'activity',
        type: 'poem',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'activity/breakdown',
        type: 'breakdown',
      },
      {
        active: false,
        disabled: true,
        displayMode: 'SELF',
        open: true,
        stage: 'checkpoint?id=1',
        type: 'survey',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'outro',
        type: 'outro',
      },
    ],
    open: false,
    roster: ['and.d.markham@gmail.com', 'jayne.phillips61@gmail.com'],
    SELStructure: 'identity',
    updatedAt: '2020-12-17T07:44:51.437Z',
  },
  {
    complete: false,
    courseID: '1',
    createdAt: '2020-08-28T14:57:27.249Z',
    displayData: {
      breakdownComponent: '',
    },
    expectedEndDate: '2020-12-22',
    expectedStartDate: '2020-12-22',
    id: '4',
    lessonID: '4',
    lessonPlan: [
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'intro',
        type: 'intro',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'warmup',
        type: 'truthgame',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'warmup/breakdown',
        type: 'breakdown',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'corelesson',
        type: 'lyrics',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'corelesson/breakdown',
        type: 'breakdown',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'activity',
        type: 'poem',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'activity/breakdown',
        type: 'breakdown',
      },
      {
        active: false,
        disabled: true,
        displayMode: 'SELF',
        open: false,
        stage: 'checkpoint?id=1',
        type: 'survey',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'outro',
        type: 'outro',
      },
    ],
    open: false,
    roster: ['and.d.markham@gmail.com', 'jayne.phillips61@gmail.com'],
    SELStructure: 'identity',
    updatedAt: '2020-10-21T09:16:19.102Z',
  },
  {
    complete: false,
    courseID: '1',
    createdAt: '2020-08-28T14:57:27.249Z',
    displayData: {
      breakdownComponent: '',
    },
    expectedEndDate: '2020-12-22',
    expectedStartDate: '2020-12-22',
    id: '5',
    lessonID: '5',
    lessonPlan: [
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'intro',
        type: 'intro',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'warmup',
        type: 'tchart',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'warmup/breakdown',
        type: 'breakdown',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'corelesson',
        type: 'lyrics',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'corelesson/breakdown',
        type: 'breakdown',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'activity',
        type: 'poem',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'activity/breakdown',
        type: 'breakdown',
      },
      {
        active: false,
        disabled: true,
        displayMode: 'SELF',
        open: false,
        stage: 'checkpoint?id=1',
        type: 'survey',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'outro',
        type: 'outro',
      },
    ],
    open: false,
    roster: ['and.d.markham@gmail.com', 'jayne.phillips61@gmail.com'],
    SELStructure: 'identity',
    updatedAt: '2020-10-21T09:16:19.102Z',
  },
  {
    complete: false,
    courseID: '1',
    createdAt: '2020-08-28T14:57:27.249Z',
    displayData: {
      breakdownComponent: '',
    },
    expectedEndDate: '2020-12-22',
    expectedStartDate: '2020-12-22',
    id: '6',
    lessonID: '6',
    lessonPlan: [
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'intro',
        type: 'intro',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'warmup',
        type: 'list',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'warmup/breakdown',
        type: 'breakdown',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'corelesson',
        type: 'lyrics',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'corelesson/breakdown',
        type: 'breakdown',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'activity',
        type: 'poem',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'activity/breakdown',
        type: 'breakdown',
      },
      {
        active: false,
        disabled: true,
        displayMode: 'SELF',
        open: false,
        stage: 'checkpoint?id=1',
        type: 'survey',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'outro',
        type: 'outro',
      },
    ],
    open: false,
    roster: ['and.d.markham@gmail.com', 'jayne.phillips61@gmail.com'],
    SELStructure: 'identity',
    updatedAt: '2020-10-21T09:16:19.102Z',
  },
  {
    complete: false,
    courseID: '1',
    createdAt: '2020-08-28T14:57:27.249Z',
    displayData: {
      breakdownComponent: '',
    },
    expectedEndDate: '2020-12-22',
    expectedStartDate: '2020-12-22',
    id: '7',
    lessonID: '7',
    lessonPlan: [
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'intro',
        type: 'intro',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'warmup',
        type: 'poll',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'warmup/breakdown',
        type: 'breakdown',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'corelesson',
        type: 'lyrics',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'corelesson/breakdown',
        type: 'breakdown',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'activity',
        type: 'poem',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'activity/breakdown',
        type: 'breakdown',
      },
      {
        active: false,
        disabled: true,
        displayMode: 'SELF',
        open: false,
        stage: 'checkpoint?id=1',
        type: 'survey',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'outro',
        type: 'outro',
      },
    ],
    open: false,
    roster: ['and.d.markham@gmail.com', 'jayne.phillips61@gmail.com'],
    SELStructure: 'identity',
    updatedAt: '2021-01-12T08:45:37.545Z',
  },
  {
    complete: false,
    courseID: '1',
    createdAt: '2020-08-28T14:57:27.249Z',
    displayData: {
      breakdownComponent: '',
    },
    expectedEndDate: '2020-12-22',
    expectedStartDate: '2020-12-22',
    id: '8',
    lessonID: '8',
    lessonPlan: [
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'intro',
        type: 'intro',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'warmup',
        type: 'list',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'warmup/breakdown',
        type: 'breakdown',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'corelesson',
        type: 'lyrics',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'corelesson/breakdown',
        type: 'breakdown',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'activity',
        type: 'poem',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'activity/breakdown',
        type: 'breakdown',
      },
      {
        active: false,
        disabled: true,
        displayMode: 'SELF',
        open: false,
        stage: 'checkpoint?id=1',
        type: 'survey',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'outro',
        type: 'outro',
      },
    ],
    open: false,
    roster: ['and.d.markham@gmail.com', 'jayne.phillips61@gmail.com'],
    SELStructure: 'identity',
    updatedAt: '2021-01-13T16:01:42.145Z',
  },
  {
    courseID: '1',
    createdAt: '2020-08-28T14:57:27.249Z',
    displayData: {
      breakdownComponent: '',
    },
    id: 'on-boarding-survey-1',
    lessonID: 'on-boarding-survey-1',
    lessonPlan: [
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: false,
        stage: '',
        type: 'intro',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'checkpoint?id=2',
        type: 'survey',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'checkpoint?id=3',
        type: 'survey',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'checkpoint?id=4',
        type: 'survey',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'checkpoint?id=5',
        type: 'survey',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'checkpoint?id=6',
        type: 'survey',
      },
      {
        active: false,
        disabled: false,
        displayMode: 'SELF',
        open: true,
        stage: 'outro',
        type: 'outro',
      },
    ],
    open: true,
    roster: ['and.d.markham@gmail.com', 'jayne.phillips61@gmail.com'],
    updatedAt: '2020-09-28T11:00:05.469Z',
  },
];
