export const lessonState = {
  status: '',
  universalLessonID: '',
  universalLessonPageID: '',
  universalStudentDataID: '',
  studentAuthID: '',
  studentUsername: '',
  lessonData: {},
  currentPage: '',
  lessonProgress: '',
  canContinue: '',
  studentData: [{}],
  viewing: false,
  displayData: [{}],
  questionData: {},
  questionDataUpdate: {},
  saveCount: '0',
  firstSave: true,
  subscription: {},
  subscribeFunc: () => {},
};
