/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d604ed31-4c20-440c-bfd8-4207f3ccb2b7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_jNgXBFd1o",
    "aws_user_pools_web_client_id": "1hj7i8g22g21bahhegja4ath6d",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xcvfgyl75nhcnaaay35kmqvuka.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-7j4nhhaq7nbgrbt42zn6spmx5m",
    "aws_user_files_s3_bucket": "iconoclaststorage83444-uatenv",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "personapi",
            "endpoint": "https://lmsesew1bl.execute-api.us-east-1.amazonaws.com/uatenv",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
