/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9a1b4916-915e-4b65-a2c7-b2286ecc16fd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_MVf87ox0v",
    "aws_user_pools_web_client_id": "79bnbhng10ml2ucaur9vuie7vi",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "EMAIL"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://xcvfgyl75nhcnaaay35kmqvuka.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-7j4nhhaq7nbgrbt42zn6spmx5m",
    "aws_user_files_s3_bucket": "iconoclaststorage83444-uatenv",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "geo": {
        "amazon_location_service": {
            "region": "us-east-1",
            "maps": {
                "items": {
                    "lmsMap-uatenv": {
                        "style": "VectorEsriLightGrayCanvas"
                    }
                },
                "default": "lmsMap-uatenv"
            }
        }
    }
};


export default awsmobile;
