#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run set-dictionary
git add ./src/dictionary/dictionary.demo.tsx
git add ./src/dictionary/dictionary.curate.tsx
git commit -m "Update dictionary"
echo "Setting dictionary..."
